### ISSUE TITLE
ParallaxTerrainProvider - getParallaxChunk()

### ISSUE THREAD

**Issue by FluffyDiscord** [VolmitSoftware/Iris#128]
**Describe the bug**
Pregen crashes itself, when scanning/catching up from the previous session.

**To Reproduce**
1. /mvc stonks5 NORMAL -g Iris
2. /mv tp stonks5
3. /iris pregen 10000
4. Wait about 10 minutes
5. Press P to pause
6. Stop the server
7. Start the server again
8. /iris pregen 10000

**Expected behavior**
Work/to not crash

**Server and Plugin Informations**
 - Installed plugins: Multiverse-Core-4.2.2.jar
 - Iris Version: Iris-1.0.25.jar
 - Server Platform and Version: Paper 1.16.3 (246)
 - Operating System (if applicable): Win 10 64x

**Additional context**

[crash.txt](https://github.com/VolmitSoftware/Iris/files/5434576/crash-2020-10-25_11.05.38-server.txt)
[console.log](https://github.com/VolmitSoftware/Iris/files/5434579/2020-10-25-3.log)

[paper.yml.txt](https://github.com/VolmitSoftware/Iris/files/5434595/paper.yml.txt)
[server.properties.txt](https://github.com/VolmitSoftware/Iris/files/5434596/server.properties.txt)
[settings.json.txt](https://github.com/VolmitSoftware/Iris/files/5434597/settings.json.txt)

**Comment by svdgoor** [comment]
@FluffyDiscord Can you try this with /iris create instead of /mvc and report back if the same issue occurs? We will look into the matter regardless, but if it can be avoided by using proper Iris commands, we can at least tell users that.

**Comment by FluffyDiscord** [comment]
Seems like it's not really related to multiverse. Someone had the same error.

![image](https://user-images.githubusercontent.com/10332247/97094886-88536800-1659-11eb-9da5-b48faa0b91ba.png)

![image](https://user-images.githubusercontent.com/10332247/97095101-9f935500-165b-11eb-95fb-aeaa9e0c53e4.png)

their crash log https://pastebin.com/3T8nNapA

**Comment by svdgoor** [comment]
Thanks for the extra info. I'll assign Dan.

**Comment by cyberpwnn** [comment]
I think this was a stall because of VolmitSoftware/Iris#135 which was just fixed. When 1.0.26 comes out try this again.

**Comment by PugglesLesser** [comment]
Updated to 1.0.26, still crashing. Only happens when players load specific chunks for some reason. I loaded into a brand new world and it's not crashing. I can also load other new chunks and they work just fine.

**Comment by cyberpwnn** [comment]
Interesting. The parallax map should NEVER be null. The only time it could theoretically be null is before the world is ready (world load or world create). But ..... hmmm ill add in some form of failsafe incase it happens. (1.0.28)
