### ISSUE TITLE
Structures Flatten in certain conditions

### ISSUE THREAD

**Issue by Skizzles** [VolmitSoftware/Iris#196]
**Describe the bug**
Trees, Buildings, etc do not generate correctly and seem to flatten out in certain conditions.

**To Reproduce**
Not quite sure how to reproduce as I am new to using Iris but a lot of different instances seem to occur.

**Expected behavior**
I expected them to not be flat and spawn correctly, however am patient : )

**Screenshots or Video Recordings**
https://screenshots.skizzles.me/wAnA3/CaGUNAYo94.jpg
https://screenshots.skizzles.me/wAnA3/HOFiDEca33.jpg

**Server and Plugin Informations**
 - Installed plugins: https://screenshots.skizzles.me/wAnA3/RajUleZO43.png
 - Iris Version: 1.1.3-1.1.5
 - Server Platform and Version [eg: PaperSpigot 1.16.3 #240]: Yatopia 1.16.4 #12 (Paper fork)
 - Operating System (if applicable): Linux (Ubuntu)
 - Server Logs: N/A

**Additional context**
Not sure what else would be needed however please let me know if more info is needed!

[**EDITED BY PSYCHO TO ADD LATEST VERSION DATE**]

**Comment by astrsh** [comment]
Seems to be non-deterministic. Here's the same two spots, one with broken objects and one without.

![2020-12-02_11 50 54](https://user-images.githubusercontent.com/73215501/100814229-570a5b00-3495-11eb-98d5-59c0fc18bb81.png)
![2020-12-02_11 53 52](https://user-images.githubusercontent.com/73215501/100814234-596cb500-3495-11eb-9f7e-c59e6065e906.png)

**Comment by cyberpwnn** [comment]
Was this perhaps on a restart, was that area the border of your world before, once loaded again resumed generating further out? if so, try the latest update... may have fixed it

**Comment by astrsh** [comment]
Above screenshots happened after creating a studio world and using std goto with no restart in between @cyberpwnn

**Comment by Skizzles** [comment]
Hello @cyberpwnn,

This was a freshly generated environment without a World Border for me. It occurs all over the world.

**Comment by svdgoor** [comment]
![afbeelding](https://user-images.githubusercontent.com/65736624/101377223-d8a52300-38b1-11eb-92f7-7c23e3671270.png)
Still happens on 1.1.5, unfortuantely.

**Comment by CocoTheOwner** [comment]
![Uploading afbeelding.png…]()

**Comment by svdgoor** [comment]
![afbeelding](https://user-images.githubusercontent.com/65736624/101416169-8e3f9880-38e9-11eb-847f-2523afc8bc54.png)

**Comment by NextdoorPsycho** [comment]
aware of the issue, looking to reproduce.

**Comment by svdgoor** [comment]
Can be reproduced. Happens when pregenerating a world mainly. Flying around can cause the issue as well when generating chunks fast. 

Lead theorys:
- The caching is overloaded / cannot keep up
- The CPU is doing something very weird when running on 100% constantly generating.

**Comment by svdgoor** [comment]
We cannot seem to recreate this when flying slowly through the map.

**Comment by svdgoor** [comment]
![afbeelding](https://user-images.githubusercontent.com/65736624/101422125-33606e00-38f6-11eb-96c4-a750c8018756.png)
Same location as the previous one just worse this time round

**Comment by astrsh** [comment]
Chunks that spawn without blocks from objects or decorators seem to show up according to a style.
I've noticed that the broken chunks generate in lines akin to the vascular generator kinda like this: 
![image](https://user-images.githubusercontent.com/73215501/101437475-63465a80-3964-11eb-93e9-03cf7a1aae5e.png)
The splits aren't clear, but you can see the lines of broken chunks here marked with redstone blocks https://gfycat.com/shoddyfocusedhermitcrab

**Comment by astrsh** [comment]
After playing around with decorators, I managed to recreate it somewhat predictably by hotloading changes then flying to the border where transitions from chunks generated using the old changed to chunks generate with the new changes. I thought that it was a vascular style but it actually seems to be occurring on chunks that border between two areas generated between different hotloads. It however didn't happen every hotload, and also seems to happen in worlds that don't hotload anything (like pregens) which also has me confused

**Comment by cyberpwnn** [comment]
I think i've fixed it. Once tested by a lot of people i'll close it.

**Comment by astrsh** [comment]
Still seems to happen in 1.1.7 😥 - will investigate further when I can

**Comment by vitaeum** [comment]
I still have this problem after pregenerating a world. It's happened every time I tried pregenning, which I have done five times now, so it seems consistently reproducable.

**Comment by AZFire1** [comment]
Yes, it's still very common when pregenerating.. I agree.

**Comment by svdgoor** [comment]
Still happens on latest, with and without pre-generating, with and without using Gleam.

**Comment by svdgoor** [comment]
Seems to have been resolved with recent updates. Please let us know if this is still happening.

**Comment by cyberpwnn** [comment]
yAY! I need to rewrite the structure system!

**Comment by svdgoor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Flattening structures](https://trello.com/c/LtJBap0u/10-flattening-structures)

**Comment by svdgoor** [comment]
(Priority markers are no longer in use on the issue tracker but only on the Trello board.)

**Comment by cyberpwnn** [comment]
I cant cause it anymore ive been testing for hours. Hopefully 1.2 fixes this!
