### ISSUE TITLE
Allow perfect (or close too) mirroring of dimensions

### ISSUE THREAD

**Issue by CalebGitBritannia** [VolmitSoftware/Iris#206]
**Is your feature request related to a problem? Please describe.**
There is currently an issue where there is a prevalent rock layer between dimensions (when mirroring), I would like to see the ability once this is patched to perfectly mirror dimensions meaning they touch without a bedrock layer between.

**Describe the solution you'd like**
When a dimension is mirrored on top of another dimension there to be no bedrock layer or gap between the two, so they touch perfectly

**Describe alternatives you've considered**
Another solution could be to make it so the middle only forms if there are blocks directly above and below

**Additional context**
https://media.discordapp.net/attachments/295197386609917953/787274277170184202/2020-12-10_12.36.38.png

^ This is an example of the issue, I used a carve layer to remove the rock palette but it would be nice to allow them to touch.

**Comment by svdgoor** [comment]
Related to VolmitSoftware/IrisPlugin#259 
EDIT: Assuming this will be autofixed with that being fixed. Leaving this open to make sure it does, though.

**Comment by svdgoor** [comment]
Looking for more info on this.

**Comment by svdgoor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dimension mirroring leaving air](https://trello.com/c/j6zTAxuX/7-dimension-mirroring-leaving-air)

**Comment by ghost** [comment]
Should be fixed with v1.2.1 otherwise will be reopened
Edit: Caleb tested it and the issue is fixed

**Comment by ghost** [comment]
https://discord.com/channels/189665083817852928/768582615078010910/795130498371682335

**Comment by JamesThack** [comment]
Would it help if I attached the files I used to create this bug?

**Comment by svdgoor** [comment]
Afaik the latest patch resolved these issues. Let me know if it still happens

**Comment by JamesThack** [comment]
Tested with the 1.2.3 and it still persists, discord link below.

https://discord.com/channels/189665083817852928/768582615078010910/795766496043335722

**Comment by JamesThack** [comment]
Any update on this issue?

**Comment by svdgoor** [comment]
Not in these updates...

**Comment by svdgoor** [comment]
Seems to have been resolved @CalebGitBritannia 
![image](https://user-images.githubusercontent.com/65736624/104930083-fa132780-59a4-11eb-82b0-de48e4dd5191.png) let me know if my test wasn't a proper one and we'll reinvestigate.

**Comment by JamesThack** [comment]
Really hate to say this but it is still persisting, I will link my pack so you can trial with mine maybe?

https://discord.com/channels/189665083817852928/768582615078010910/800776965039718442
