### ISSUE TITLE
Chunk holes baby

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#452]
![image](https://user-images.githubusercontent.com/65736624/126401012-75625c9c-9bee-428e-a7c0-e93c9c3f0834.png)

[latest_-_2021-07-20T170252.785.log](https://github.com/VolmitSoftware/Iris/files/6851475/latest_-_2021-07-20T170252.785.log)

`/ir what biome` returns non-iris biome, while clearly an Iris world.

**Comment by svdgoor** [comment]
[2021-07-20-8.log](https://github.com/VolmitSoftware/Iris/files/6851480/2021-07-20-8.log)

**Comment by ghost** [comment]
I think this is fixed now @CocoTheOwner

**Comment by StrangeOne101** [comment]
Doesn't appear to be fixed. 

![](https://I.imgur.com/h3Ixn0G.png)

![](https://images-ext-2.discordapp.net/external/wzYrdQL7e-OiZxcRxqjvS2A_5XNYqJKrehSFEK8mJYw/https/i.imgur.com/imtGLFF.png)
)

This was pregened on 1.5.10

Build Paper-71

**Comment by svdgoor** [comment]
@NextdoorPsycho can you please send a render of the world you generated, so it may be either shown there are no chunk holes in it, or to confirm they are still an issue?

**Comment by cyberpwnn** [comment]
Unable to cause these anymore since 1.5.9. This was recorded on 1.3.7 or something around there. It looks like you're using 1.16.5 and not the latest. We have moved on and continued Iris development on the latest version of Minecraft. However we have been working on 1.16.5 support for Iris 1.5+, but this is a #wontfix for 1.3 issues on 1.16, but we might fix it by adding support for 1.16 on latest.

**Comment by svdgoor** [comment]
Apart from Spigot not providing chunks to the player, I haven't seen these as of late. So lets hope they're actually, properly, gone.
Please, if someone opens a new issue for chunk holes, close that with a mention here, and reopen this.
